# web服务设置
server:
  port: 8888
  context-path: /

# DateSource
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: "xpeng,2202"
  security:
    user:
      name: admin
      password: admin123

# TODO
#    dynamic: # 动态数据源框架
#      primary: master # 默认数据源
#      strict: false # 关闭严格模式（找不到指定数据时不报错）
#      lazy: true # 懒加载，不访问不初始化
#      datasource:
#        # 主库
#        master:
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/shared_case?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: root
#          password: "xpeng,2202"
#        # 从库
#        slave:
#          driverClassName: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/hospital?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#          username: root
#          password: "xpeng,2202"

mybatis-plus:
  mapper-locations: class*:mapper/**/*.xml
  type-aliases-package: com.sharedcase.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# ipfs 配置
ipfs:
  url: http://127.0.0.1:5001
  multiAddr: /ip4/127.0.0.1/tcp/5001
  gateway: https://ipfs.io/ipfs/

#  FISCO-BCOS
fisco:
  # FISCO-BCOS SDK配置文件路径, 文件系统的绝对路径
  sdkConfigPath: D:\Projects\lessonprojects\sharedcase\backend\src\main\resources\sdk\config.toml
  contract:
    addresses:
      userRegistry: "0xd24180cc0fef2f3e545de4f9aafc09345cd08903"
      caseContract: "0x19a6434154de51c7a7406edf312f01527441b561"


contract:
  case:

# 是否开启swagger
swagger:
  enabled: true
